# Generated by Django 3.1 on 2022-02-28 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20220228_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
