# Generated by Django 3.1 on 2022-02-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20220228_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('best', 'best'), ('special', 'special')], max_length=20),
        ),
    ]
