# Generated by Django 3.1 on 2022-02-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_auto_20220228_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categorytype',
            field=models.CharField(choices=[('Men', 'Men'), ('Kid', 'Kid')], default='Fun', max_length=20),
        ),
    ]
