# Generated by Django 3.1 on 2022-03-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_auto_20220228_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, default='product2/11.jpg', upload_to='product2/'),
        ),
    ]
